2018-05-04 01:46:16,025 INFO: Microblog startup [in /home/bberastain/Desktop/microblog/app/__init__.py:48]
2018-05-04 01:56:49,572 INFO: Microblog startup [in /home/bberastain/Desktop/microblog/app/__init__.py:48]
2018-05-04 02:01:50,541 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1MjU0MjUwOTMuMTAwMzAwMywicmVzZXRfcGFzc3dvcmQiOjF9.grVRm0OivvwlYWbWuJoL9QgSa8HgNiPTjQpVBsY7_kg [GET] [in /home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/bberastain/Desktop/microblog/app/routes.py", line 168, in reset_password
    form = ResetPasswordForm()
NameError: name 'ResetPasswordForm' is not defined
2018-05-04 02:08:10,100 INFO: Microblog startup [in /home/bberastain/Desktop/microblog/app/__init__.py:48]
2018-05-04 02:14:11,090 INFO: Microblog startup [in /home/bberastain/Desktop/microblog/app/__init__.py:48]
2018-05-04 02:15:28,920 INFO: Microblog startup [in /home/bberastain/Desktop/microblog/app/__init__.py:48]
2018-05-04 12:42:10,508 INFO: Microblog startup [in /home/bberastain/Desktop/microblog/app/__init__.py:50]
2018-05-04 12:42:13,783 ERROR: Exception on /login [GET] [in /home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/bberastain/Desktop/microblog/app/routes.py", line 48, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/bberastain/Desktop/microblog/app/templates/login.html", line 3, in template
    {% block_app content %}
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 144, in parse_statement
    self.fail_unknown_tag(token.value, token.lineno)
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 97, in fail_unknown_tag
    return self._fail_ut_eof(name, self._end_token_stack, lineno)
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 90, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'block_app'.
