2018-04-13 00:22:13,672 INFO: Microblog startup [in /home/bberastain/Desktop/microblog/app/__init__.py:46]
2018-04-13 00:22:24,876 ERROR: Exception on /edit_profile [GET] [in /home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/bberastain/Desktop/microblog/app/routes.py", line 80, in edit_profile
    form = EditProfileForm()
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'original_username'
2018-04-13 00:22:32,987 ERROR: Exception on /edit_profile [GET] [in /home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/bberastain/Desktop/microblog/app/routes.py", line 80, in edit_profile
    form = EditProfileForm()
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'original_username'
2018-04-13 00:22:50,591 ERROR: Exception on /edit_profile [GET] [in /home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/bberastain/Desktop/microblog/app/routes.py", line 80, in edit_profile
    form = EditProfileForm()
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'original_username'
2018-04-13 00:23:40,840 ERROR: Exception on /edit_profile [GET] [in /home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/bberastain/Desktop/microblog/app/routes.py", line 80, in edit_profile
    form = EditProfileForm(current_user.username)
  File "/home/bberastain/Desktop/microblog/venv/lib/python3.5/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'original_username'
2018-04-13 01:58:20,834 INFO: Microblog startup [in /home/bberastain/Desktop/microblog/app/__init__.py:46]
2018-04-20 15:45:14,542 INFO: Microblog startup [in /home/bberastain/Desktop/microblog/app/__init__.py:46]
2018-04-23 13:59:58,268 INFO: Microblog startup [in /home/bberastain/Desktop/microblog/app/__init__.py:46]
2018-04-23 14:00:03,888 INFO: Microblog startup [in /home/bberastain/Desktop/microblog/app/__init__.py:46]
2018-04-23 14:06:56,485 INFO: Microblog startup [in /home/bberastain/Desktop/microblog/app/__init__.py:46]
2018-04-23 15:06:06,086 INFO: Microblog startup [in /home/bberastain/Desktop/microblog/app/__init__.py:46]
2018-04-23 15:06:44,779 INFO: Microblog startup [in /home/bberastain/Desktop/microblog/app/__init__.py:46]
2018-04-23 15:07:33,545 INFO: Microblog startup [in /home/bberastain/Desktop/microblog/app/__init__.py:46]
2018-04-23 15:08:50,279 INFO: Microblog startup [in /home/bberastain/Desktop/microblog/app/__init__.py:46]
2018-04-23 15:10:58,488 INFO: Microblog startup [in /home/bberastain/Desktop/microblog/app/__init__.py:46]
2018-04-23 15:13:55,792 INFO: Microblog startup [in /home/bberastain/Desktop/microblog/app/__init__.py:46]
2018-04-23 15:30:27,976 INFO: Microblog startup [in /home/bberastain/Desktop/microblog/app/__init__.py:46]
2018-04-23 15:30:39,838 INFO: Microblog startup [in /home/bberastain/Desktop/microblog/app/__init__.py:46]
2018-04-23 15:35:45,147 INFO: Microblog startup [in /home/bberastain/Desktop/microblog/app/__init__.py:46]
2018-04-23 15:36:35,244 INFO: Microblog startup [in /home/bberastain/Desktop/microblog/app/__init__.py:46]
2018-04-23 15:55:27,228 INFO: Microblog startup [in /home/bberastain/Desktop/microblog/app/__init__.py:46]
2018-04-23 16:05:22,183 INFO: Microblog startup [in /home/bberastain/Desktop/microblog/app/__init__.py:46]
2018-04-23 16:20:35,359 INFO: Microblog startup [in /home/bberastain/Desktop/microblog/app/__init__.py:46]
2018-04-23 16:20:56,310 INFO: Microblog startup [in /home/bberastain/Desktop/microblog/app/__init__.py:46]
2018-04-23 16:21:09,555 INFO: Microblog startup [in /home/bberastain/Desktop/microblog/app/__init__.py:46]
2018-04-23 16:24:26,134 INFO: Microblog startup [in /home/bberastain/Desktop/microblog/app/__init__.py:46]
2018-04-23 16:27:27,218 INFO: Microblog startup [in /home/bberastain/Desktop/microblog/app/__init__.py:46]
2018-04-23 16:27:48,926 INFO: Microblog startup [in /home/bberastain/Desktop/microblog/app/__init__.py:46]
2018-04-23 16:28:40,579 INFO: Microblog startup [in /home/bberastain/Desktop/microblog/app/__init__.py:46]
2018-04-24 00:18:23,042 INFO: Microblog startup [in /home/bberastain/Desktop/microblog/app/__init__.py:46]
2018-04-25 11:38:04,214 INFO: Microblog startup [in /home/bberastain/Desktop/microblog/app/__init__.py:46]
2018-04-25 11:40:19,133 INFO: Microblog startup [in /home/bberastain/Desktop/microblog/app/__init__.py:46]
2018-04-25 11:40:28,717 INFO: Microblog startup [in /home/bberastain/Desktop/microblog/app/__init__.py:46]
2018-04-25 18:05:13,126 INFO: Microblog startup [in /Users/vanyroca/Desktop/BrunoCompSci/app/__init__.py:46]
2018-04-26 15:47:23,734 INFO: Microblog startup [in /Users/vanyroca/Desktop/BrunoCompSci/app/__init__.py:46]
